### PR TITLE
Add chewypiano.png

### PR DESCRIPTION
**Pull request by chewypiano**

### CODE REVIEW

**Comment by aidoxe-123** [comment]
The CI test says that you are missing the shadow plugins

**Comment by JoeyChenSmart** [comment]
> The CI test says that you are missing the shadow plugins

Seems like a github actions issue. This happens from time to time.

Closing and reopening the PR should restart the CI process (hopefully fixing this).

**Comment by chewypiano** [comment]
> > The CI test says that you are missing the shadow plugins
> 
> Seems like a github actions issue. This happens from time to time.
> 
> Closing and reopening the PR should restart the CI process (hopefully fixing this).

Noted with thanks.

**Review by JoeyChenSmart — APPROVED** [review]
LGTM 👍 💯

**Pull request merged**
